swagger: "2.0"
info:
  version: "1.0.0"
  title: "Cart API"
paths:
  /api/carts/{cid}:
    get:
      summary: "Get cart by id"
      description: "Returns cart content by id"
      tags:
      - "cart"
      parameters:
        - name: "cid"
          in: "path"
          description: "Cart ID"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/components/schemas/Cart"
  /api/carts:
    post:
      summary: "Create a new cart"
      description: "Creates a new cart"
      tags:
      - "cart"
      parameters:
        - name: "cart"
          in: "body"
          description: "Cart object"
          required: true
          schema:
            $ref: "#/components/schemas/Cart"
      responses:
        201:
          description: "Cart created"
          schema:
            $ref: "#/components/schemas/Cart"
/api/carts/{cid}/product/{pid}:
    post:
      summary: "Add product to cart"
      description: "Adds a product to a cart. You can't test this endpoint without being logged in"
      tags:
      - "cart"
      parameters:
        - name: "cid"
          in: "path"
          description: "Cart ID"
          required: true
          type: "string"
        - name: "pid"
          in: "path"
          description: "Product ID"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/components/schemas/Cart"
    put:
      summary: "Update product quantity"
      description: "Updates a product quantity in a cart."
      tags:
      - "cart"
      parameters:
        - name: "cid"
          in: "path"
          description: "Cart ID"
          required: true
          type: "string"
        - name: "pid"
          in: "path"
          description: "Product ID"
          required: true
          type: "string"
        - name: "quantity"
          in: "body"
          description: "Quantity object"
          required: true
          schema:
            type: "object"
            properties:
              quantity:
                type: "integer"
                description: "Product quantity"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/components/schemas/Cart"
    delete:
      summary: "Delete product from cart"
      description: "Deletes a product from a cart."
      tags:
      - "cart"
      parameters:
        - name: "cid"
          in: "path"
          description: "Cart ID"
          required: true
          type: "string"
        - name: "pid"
          in: "path"
          description: "Product ID"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/components/schemas/Cart"
/api/carts/{cid}:
  put:
    summary: "Update cart"
    description: "Updates a cart"
    tags:
      - "cart"
    parameters:
      - name: "cid"
        in: "path"
        description: "Cart ID"
        required: true
        type: "string"
      - name: "cart"
        in: "body"
        description: "Cart object"
        required: true
        schema:
          $ref: "#/components/schemas/Cart"
    responses:
      200:
        description: "Successful operation"
        schema:
          $ref: "#/components/schemas/Cart"
      404:
        description: "Cart not found or malformed product array"
  delete:
    summary: "Delete cart"
    description: "Deletes a cart"
    tags:
      - "cart"
    parameters:
      - name: "cid"
        in: "path"
        description: "Cart ID"
        required: true
        type: "string"
    responses:
      200:
        description: "Successful operation"
        schema:
          $ref: "#/components/schemas/Cart"
      404:
        description: "Cart not found"
components:
  schemas:
    Cart:
      type: "object"
      properties:
        _id:
          type: "string"
          description: "Cart ID autogenerated by MongoDB"
        products:
          type: "array"
          items:
            type: "object"
            properties:
              product:
                type: "string"
                description: "Product ID"
              quantity:
                type: "integer"
                description: "Product quantity"
          description: "Array containing products id's and quantities"